services:
  backend:
    environment:
      APP_ENV: development
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    command: npm run dev
    environment:
      NODE_ENV: development
